name        : libraw1394
version     : 2.0.5
release     : 2
source      :
    - http://downloads.sourceforge.net/libraw1394/libraw1394-2.0.5.tar.gz : 50e7b812f09ec8181fc060e7e25e260017c16c1b41a04c51e23446f26fa109d4
homepage    : http://sourceforge.net/projects/libraw1394/
license     :
    - LGPL-2.1
summary     :
    - Library providing raw IEE1394 support to userspace
    - utils: libraw1394 command line utilities
component   :
    - multimedia.codecs
    - utils: programming.tools
patterns    :
    - utils:
        - /usr/bin
        - /usr/share/doc
        - /usr/share/man
description : |
    libraw1394 provides direct access to the IEEE 1394 bus through the Linux 1394 subsystem's raw1394 user space interface.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
