name       : libraw1394
version    : 2.1.2
release    : 3
source     :
    - https://www.kernel.org/pub/linux/libs/ieee1394/libraw1394-2.1.2.tar.xz : 03ccc69761d22c7deb1127fc301010dd13e70e44bb7134b8ff0d07590259a55e
license    : LGPL-2.1-or-later
component  :
    - multimedia.codecs
    - utils : programming.tools
summary    :
    - Library providing raw IEE1394 support to userspace
    - utils : libraw1394 command line utilities
description: |
    libraw1394 provides direct access to the IEEE 1394 bus through the Linux 1394 subsystem's raw1394 user space interface.
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/doc
        - /usr/share/man
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
